[package]
name = "wasmboy-cli"
version = "0.0.1"
authors = ["Richard Anaya"]
edition = "2018"
license = "MIT"
description = "a framebuffer runner of wasmboy games"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
